import {
  assertValidPhase20Topics,
  type Phase20Difficulty,
  type Phase20Subject,
  type Phase20Topic,
} from "@/domain/scientific-content/phase20";

const prerequisite = (subject: Phase20Subject, slug: string): string => `${subject}:${slug}`;

function topic(
  subjectSlug: Phase20Subject,
  slug: string,
  name: string,
  description: string,
  minimumGrade: number,
  maximumGrade: number,
  difficulty: Phase20Difficulty,
  formula: string,
  formulaLabel: string,
  workedExample: string,
  application: string,
  misconception: string,
  prerequisiteKeys: readonly string[] = [],
): Phase20Topic {
  return {
    key: `${subjectSlug}:${slug}`,
    slug,
    name,
    subjectSlug,
    domainId: `domain-${slug}`,
    description,
    minimumGrade,
    maximumGrade,
    difficulty,
    prerequisiteKeys,
    formula,
    formulaLabel,
    workedExample,
    application,
    misconception,
    sourceAttribution:
      "Mathios Phase 20 reference package; a curriculum-aligned synthesis for local educational use. Educators should review local standards and primary sources before external publication.",
  };
}

const mathematicsTopics: Phase20Topic[] = [
  topic(
    "mathematics",
    "arithmetic",
    "Arithmetic",
    "Use whole numbers, fractions, ratios, and estimation to reason about quantity.",
    6,
    8,
    "gentle",
    String.raw`a+b=c`,
    "The sum of a and b equals c",
    "A recipe uses 3/4 cup of water twice, so the total is 3/2 cups.",
    "Arithmetic supports measurement, budgeting, scaling, and every quantitative science subject.",
    "A fraction is not a pair of unrelated whole numbers; its numerator and denominator form one ratio.",
  ),
  topic(
    "mathematics",
    "algebra",
    "Algebra",
    "Represent unknown quantities with symbols and transform equations while preserving equality.",
    7,
    10,
    "balanced",
    String.raw`ax+b=c`,
    "a times x plus b equals c",
    "Solving 2x + 3 = 11 gives x = 4 after subtracting 3 and dividing by 2.",
    "Algebra turns physical laws and scientific relationships into models that can be solved.",
    "Changing one side of an equation without making the same change to the other side preserves no equality.",
    [prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "mathematics",
    "geometry",
    "Geometry",
    "Use definitions, measurement, symmetry, and proof to describe shape and space.",
    7,
    10,
    "balanced",
    String.raw`A=\frac{bh}{2}`,
    "The area of a triangle equals base times height divided by two",
    "A triangle with base 8 cm and height 5 cm has area 20 cm².",
    "Geometry supports surveying, optics, molecular shape, map-making, and spatial modeling.",
    "The slanted side of a triangle is not automatically its perpendicular height.",
    [prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "mathematics",
    "trigonometry",
    "Trigonometry",
    "Relate angles and side lengths and recognize periodic relationships in triangles and waves.",
    9,
    12,
    "balanced",
    String.raw`\sin^2\theta+\cos^2\theta=1`,
    "Sine squared theta plus cosine squared theta equals one",
    "For a right triangle with sin θ = 3/5, the positive acute-angle cosine is 4/5.",
    "Trigonometry connects slopes, sound, light, navigation, and orbital observations.",
    "Sine and cosine are not arbitrary labels for sides; their values depend on the chosen angle and orientation.",
    [prerequisite("mathematics", "geometry")],
  ),
  topic(
    "mathematics",
    "functions",
    "Functions",
    "Treat a function as a rule that maps each allowed input to an output and analyze its behavior.",
    8,
    12,
    "balanced",
    String.raw`f(x)=y`,
    "The function of x equals y",
    "If f(x) = 2x + 1, then f(3) = 7 and the output changes by 2 for each unit input change.",
    "Functions provide a common language for models of motion, populations, reactions, and observations.",
    "A graph can pass the vertical-line test while still failing to be one-to-one.",
    [prerequisite("mathematics", "algebra")],
  ),
  topic(
    "mathematics",
    "probability",
    "Probability",
    "Quantify uncertainty, distinguish events from outcomes, and update beliefs with evidence.",
    7,
    12,
    "balanced",
    String.raw`P(A\mid B)=\frac{P(A\cap B)}{P(B)}`,
    "The probability of A given B equals the probability of A and B divided by the probability of B",
    "If P(A and B) = 0.2 and P(B) = 0.5, then P(A given B) = 0.4.",
    "Probability supports genetics, risk analysis, measurement uncertainty, and scientific inference.",
    "A likely event is not guaranteed, and a rare event is not impossible.",
    [prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "mathematics",
    "statistics",
    "Statistics",
    "Summarize data, quantify variation, and make careful claims from samples and measurements.",
    7,
    12,
    "balanced",
    String.raw`\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i`,
    "The sample mean equals the sum of observations divided by their count",
    "The mean of 2, 4, and 9 is 5 because their sum is 15 and there are 3 observations.",
    "Statistics makes experiments, public-health studies, astronomy surveys, and model evaluation measurable.",
    "A mean alone does not describe spread or prove that one variable causes another.",
    [prerequisite("mathematics", "probability")],
  ),
  topic(
    "mathematics",
    "combinatorics",
    "Combinatorics",
    "Count structured possibilities using bijections, recurrences, and the distinction between order and selection.",
    9,
    12,
    "challenging",
    String.raw`\binom{n}{k}=\frac{n!}{k!(n-k)!}`,
    "The number of unordered selections of k items from n items",
    "Choosing 2 people from 5 gives 5!/(2!3!) = 10 possible pairs.",
    "Combinatorics supports probability, algorithms, genetics, coding, and olympiad problem solving.",
    "Permutations and combinations are interchangeable; order matters for permutations but not combinations.",
    [prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "mathematics",
    "calculus",
    "Calculus",
    "Use limits, derivatives, and integrals to study continuous change and accumulation.",
    11,
    13,
    "challenging",
    String.raw`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}`,
    "The derivative is the limit of the average rate of change as h approaches zero",
    "For f(x)=x², the derivative at x=3 is 6, the instantaneous slope there.",
    "Calculus models acceleration, flow, reaction rates, optimization, and orbital motion.",
    "A derivative is not the total change over an interval; it is a local rate of change.",
    [prerequisite("mathematics", "functions"), prerequisite("mathematics", "trigonometry")],
  ),
  topic(
    "mathematics",
    "linear-algebra",
    "Linear Algebra",
    "Represent vectors and systems of linear equations and reason about transformations in multiple dimensions.",
    13,
    14,
    "challenging",
    String.raw`A\mathbf{x}=\mathbf{b}`,
    "A matrix times a vector x equals a vector b",
    "A two-variable system can be written as a matrix equation and solved by elimination or an inverse when it exists.",
    "Linear algebra powers 3D graphics, data analysis, quantum models, and numerical simulation.",
    "A matrix is not automatically a transformation; its meaning depends on the vector spaces and coordinates.",
    [prerequisite("mathematics", "algebra")],
  ),
  topic(
    "mathematics",
    "differential-equations",
    "Differential Equations",
    "Describe how an unknown function changes and use initial conditions to select a model solution.",
    13,
    14,
    "challenging",
    String.raw`\frac{dy}{dx}=ky`,
    "The rate of change of y equals a constant times y",
    "The model dy/dt = 0.2y predicts exponential growth when the initial amount is positive.",
    "Differential equations model populations, cooling, circuits, fluids, and planetary systems.",
    "An equation involving a derivative is not solved merely by differentiating it again.",
    [prerequisite("mathematics", "calculus")],
  ),
  topic(
    "mathematics",
    "number-theory",
    "Number Theory",
    "Study divisibility, primes, congruences, and the structure of the integers.",
    8,
    14,
    "challenging",
    String.raw`a\equiv b\pmod n`,
    "a is congruent to b modulo n",
    "17 is congruent to 2 modulo 5 because their difference is 15, a multiple of 5.",
    "Number theory supports cryptography, error correction, calendars, and proof-based mathematics.",
    "Congruence modulo n does not mean two integers are equal; it means their difference is divisible by n.",
    [prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "mathematics",
    "complex-numbers",
    "Complex Numbers",
    "Extend the number system with an imaginary unit and use algebra and geometry together.",
    11,
    14,
    "challenging",
    String.raw`z=a+bi,\quad |z|=\sqrt{a^2+b^2}`,
    "A complex number z equals a plus b times i and has modulus the square root of a squared plus b squared",
    "The modulus of 3 + 4i is 5, so the number is five units from the origin in the complex plane.",
    "Complex numbers simplify oscillations, circuits, waves, and polynomial equations.",
    "The imaginary unit is not meaningless; it extends arithmetic while retaining consistent rules.",
    [prerequisite("mathematics", "algebra")],
  ),
  topic(
    "mathematics",
    "discrete-mathematics",
    "Discrete Mathematics",
    "Reason about finite structures, algorithms, graphs, logic, and proof by induction.",
    10,
    14,
    "challenging",
    String.raw`\sum_{v\in V}\deg(v)=2|E|`,
    "The sum of vertex degrees in a graph equals twice the number of edges",
    "A graph with 4 edges has total vertex degree 8, regardless of how the edges are arranged.",
    "Discrete mathematics supports networks, algorithms, scheduling, data structures, and scientific computation.",
    "A graph in discrete mathematics is a set of vertices and edges, not necessarily a plotted function.",
    [prerequisite("mathematics", "algebra")],
  ),
  topic(
    "mathematics",
    "olympiad-mathematics",
    "Olympiad Mathematics",
    "Combine proof, inequalities, invariants, constructions, and creative counting in unfamiliar problems.",
    15,
    15,
    "challenging",
    String.raw`a^2+b^2\ge2ab`,
    "The sum of two squares is at least twice their product for nonnegative a and b",
    "The inequality follows from (a-b)² ≥ 0 and becomes equality when a = b.",
    "Olympiad methods sharpen proof, modeling, and persistence across all quantitative sciences.",
    "A correct numerical pattern is not a proof until the argument explains why it holds generally.",
    [prerequisite("mathematics", "combinatorics"), prerequisite("mathematics", "number-theory")],
  ),
];

const physicsTopics: Phase20Topic[] = [
  topic(
    "physics",
    "measurement",
    "Measurement",
    "Choose quantities, units, instruments, uncertainty, and significant figures to make observations reproducible.",
    7,
    9,
    "gentle",
    String.raw`\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i`,
    "The mean measurement equals the sum of repeated readings divided by their count",
    "Repeated readings of 9.8, 9.9, and 9.7 cm have mean 9.8 cm before uncertainty is reported.",
    "Measurement is the shared evidence language of physics, chemistry, biology, and astronomy.",
    "Extra decimal places do not create extra accuracy when the instrument cannot resolve them.",
    [prerequisite("mathematics", "statistics")],
  ),
  topic(
    "physics",
    "mechanics",
    "Mechanics",
    "Describe motion and interactions using position, velocity, acceleration, momentum, and energy.",
    7,
    11,
    "balanced",
    String.raw`p=mv`,
    "Momentum p equals mass m times velocity v",
    "A 2 kg cart moving at 3 m/s has momentum 6 kg m/s in the direction of motion.",
    "Mechanics explains transport, machines, sports, collisions, and planetary motion.",
    "A larger speed is not the only way to increase momentum; mass and direction also matter.",
    [prerequisite("physics", "measurement")],
  ),
  topic(
    "physics",
    "kinematics",
    "Kinematics",
    "Model position, velocity, and acceleration without yet asking which force caused the motion.",
    7,
    10,
    "balanced",
    String.raw`v=v_0+at`,
    "Final velocity equals initial velocity plus acceleration times time",
    "Starting at 4 m/s with acceleration 2 m/s² for 3 s gives final velocity 10 m/s.",
    "Kinematics supports motion sensors, traffic analysis, sports science, and introductory astronomy.",
    "Constant acceleration does not mean constant velocity; it means velocity changes at a steady rate.",
    [prerequisite("physics", "measurement")],
  ),
  topic(
    "physics",
    "dynamics",
    "Dynamics",
    "Explain changes in motion by identifying forces, free-body diagrams, and Newton's laws.",
    8,
    11,
    "balanced",
    String.raw`\sum F=ma`,
    "The net force equals mass times acceleration",
    "A net force of 12 N on a 3 kg object produces acceleration 4 m/s².",
    "Dynamics connects motion to friction, engines, structures, biomechanics, and orbits.",
    "The force in Newton's second law is the net force, not necessarily one individual force.",
    [prerequisite("physics", "kinematics")],
  ),
  topic(
    "physics",
    "energy",
    "Energy",
    "Track transfers and transformations of energy using work, kinetic energy, potential energy, and power.",
    8,
    11,
    "balanced",
    String.raw`K=\frac{1}{2}mv^2`,
    "Kinetic energy equals one half mass times speed squared",
    "Doubling a cart's speed quadruples its kinetic energy because speed is squared.",
    "Energy accounting helps compare machines, ecosystems, transport systems, and stars.",
    "Energy is not used up; it is transferred or transformed, often into less useful thermal energy.",
    [prerequisite("physics", "dynamics")],
  ),
  topic(
    "physics",
    "momentum",
    "Momentum",
    "Use vector momentum and impulse to analyze collisions and interactions in isolated systems.",
    9,
    11,
    "balanced",
    String.raw`\Delta p=J=F\Delta t`,
    "Change in momentum equals impulse, force times the interaction time",
    "A 5 N force acting for 0.4 s gives impulse 2 N s and changes momentum by 2 kg m/s.",
    "Momentum explains airbags, rocket motion, particle collisions, and recoil.",
    "Momentum is conserved only for a suitably isolated system, not necessarily for every object alone.",
    [prerequisite("physics", "dynamics")],
  ),
  topic(
    "physics",
    "rotation",
    "Rotation",
    "Analyze angular displacement, torque, moment of inertia, and rotational energy.",
    10,
    12,
    "challenging",
    String.raw`\tau=I\alpha`,
    "Torque equals moment of inertia times angular acceleration",
    "The same torque produces less angular acceleration for a wheel whose mass is distributed farther from its axis.",
    "Rotation models gears, gyroscopes, planets, engineering systems, and athletic movement.",
    "Torque is not simply force; its effect depends on the lever arm and the chosen axis.",
    [prerequisite("physics", "dynamics")],
  ),
  topic(
    "physics",
    "gravitation",
    "Gravitation",
    "Model the attraction between masses and connect surface gravity with orbital motion.",
    10,
    12,
    "challenging",
    String.raw`F=G\frac{m_1m_2}{r^2}`,
    "Gravitational force equals G times the product of the masses divided by distance squared",
    "Doubling the separation reduces the gravitational force to one quarter when the masses stay fixed.",
    "Gravitation unifies falling objects, tides, satellites, stars, and large-scale structure.",
    "Weight and mass are not the same; weight is a gravitational force while mass measures inertia.",
    [prerequisite("physics", "dynamics"), prerequisite("mathematics", "functions")],
  ),
  topic(
    "physics",
    "fluids",
    "Fluids",
    "Describe pressure, buoyancy, flow, and the behavior of liquids and gases at rest and in motion.",
    9,
    12,
    "balanced",
    String.raw`P=P_0+\rho gh`,
    "Pressure at depth equals surface pressure plus density times gravity times depth",
    "In water, pressure increases with depth because the water column above becomes taller.",
    "Fluid ideas explain weather, blood flow, ships, pumps, and planetary atmospheres.",
    "Pressure is not the same as force; pressure is force distributed over area.",
    [prerequisite("physics", "dynamics")],
  ),
  topic(
    "physics",
    "waves",
    "Waves",
    "Use amplitude, frequency, wavelength, phase, and superposition to describe energy transfer.",
    8,
    12,
    "balanced",
    String.raw`v=f\lambda`,
    "Wave speed equals frequency times wavelength",
    "A 2 Hz wave with wavelength 3 m travels at 6 m/s through the modeled medium.",
    "Waves explain sound, light, seismic signals, communication, and spectroscopy.",
    "A wave can transfer energy without transporting the medium as a whole from source to receiver.",
    [prerequisite("physics", "kinematics")],
  ),
  topic(
    "physics",
    "thermodynamics",
    "Thermodynamics",
    "Relate temperature, heat, work, internal energy, and entropy in physical systems.",
    9,
    12,
    "challenging",
    String.raw`\Delta U=Q-W`,
    "Change in internal energy equals heat added minus work done by the system",
    "If a system receives 500 J of heat and does 200 J of work, its internal energy increases by 300 J.",
    "Thermodynamics explains engines, refrigerators, climate, phase changes, and metabolism.",
    "Temperature measures average microscopic energy; it is not the total thermal energy of an object.",
    [prerequisite("physics", "measurement"), prerequisite("physics", "energy")],
  ),
  topic(
    "physics",
    "electricity",
    "Electricity",
    "Model charge, current, potential difference, resistance, and energy transfer in circuits.",
    9,
    12,
    "balanced",
    String.raw`V=IR`,
    "Potential difference equals current times resistance",
    "A 6 Ω resistor carrying 2 A has a potential difference of 12 V.",
    "Electricity supports sensors, electronics, nerve signals, power systems, and laboratory measurement.",
    "Current is not consumed by a resistor; energy is transferred while charge continues through the circuit.",
    [prerequisite("physics", "measurement")],
  ),
  topic(
    "physics",
    "magnetism",
    "Magnetism",
    "Describe magnetic fields and their forces on moving charges and currents.",
    10,
    12,
    "challenging",
    String.raw`F=qvB\sin\theta`,
    "Magnetic force equals charge times speed times field strength times the sine of the angle",
    "A charge moving parallel to a magnetic field has zero magnetic force because sin 0° is zero.",
    "Magnetism underlies motors, generators, medical imaging, compasses, and planetary magnetospheres.",
    "A stationary charge does not experience the magnetic force described by qvB sin θ.",
    [prerequisite("physics", "electricity")],
  ),
  topic(
    "physics",
    "optics",
    "Optics",
    "Explain reflection, refraction, imaging, and the wave behavior of light.",
    10,
    12,
    "balanced",
    String.raw`\frac{1}{f}=\frac{1}{d_o}+\frac{1}{d_i}`,
    "The reciprocal of focal length equals the reciprocal of object distance plus the reciprocal of image distance",
    "A converging lens with f = 10 cm and object distance 30 cm forms a real image at 15 cm.",
    "Optics supports cameras, telescopes, microscopes, fiber communication, and vision.",
    "A real image and a virtual image are not distinguished by whether light exists; they are distinguished by where rays converge.",
    [prerequisite("physics", "waves"), prerequisite("mathematics", "geometry")],
  ),
  topic(
    "physics",
    "modern-physics",
    "Modern Physics",
    "Use evidence from atomic, nuclear, quantum, and relativistic phenomena when classical models are incomplete.",
    11,
    14,
    "challenging",
    String.raw`E=mc^2`,
    "Energy equals mass times the speed of light squared",
    "A small mass change can represent a large energy change because c² is very large.",
    "Modern physics connects stars, medical imaging, semiconductors, nuclear energy, and cosmology.",
    "Relativity and quantum theory do not simply replace all classical physics; they extend its domain of validity.",
    [prerequisite("physics", "energy")],
  ),
  topic(
    "physics",
    "relativity",
    "Relativity",
    "Analyze how measurements of time, length, energy, and gravity depend on motion and spacetime structure.",
    12,
    14,
    "challenging",
    String.raw`\gamma=\frac{1}{\sqrt{1-v^2/c^2}}`,
    "Gamma equals one divided by the square root of one minus speed squared divided by light speed squared",
    "At everyday speeds v is much smaller than c, so γ is extremely close to 1 and classical models are accurate.",
    "Relativity is needed for satellite timing, particle accelerators, black holes, and high-speed observations.",
    "Relativity does not say that every observer sees every event as equally simultaneous.",
    [prerequisite("physics", "kinematics"), prerequisite("physics", "modern-physics")],
  ),
  topic(
    "physics",
    "quantum-physics",
    "Quantum Physics",
    "Use quantization, probability amplitudes, and measurement to describe microscopic systems.",
    12,
    14,
    "challenging",
    String.raw`E=hf`,
    "Photon energy equals Planck's constant times frequency",
    "Blue light has higher photon energy than red light because its frequency is higher.",
    "Quantum physics explains spectra, lasers, transistors, sensors, and the structure of matter.",
    "A probability distribution is not the same as saying that the system has no physical constraints.",
    [prerequisite("physics", "waves"), prerequisite("physics", "modern-physics")],
  ),
  topic(
    "physics",
    "nuclear-physics",
    "Nuclear Physics",
    "Describe nuclei, binding energy, radioactive decay, and nuclear reactions using conservation laws.",
    12,
    14,
    "challenging",
    String.raw`N=N_0e^{-\lambda t}`,
    "The remaining nuclei equal the initial number times e to the negative decay constant times time",
    "After one half-life, half of a large ensemble of identical unstable nuclei remains on average.",
    "Nuclear physics supports medical tracers, dating methods, energy research, and stellar nucleosynthesis.",
    "A half-life is not the time at which every nucleus decays; it describes a statistical population.",
    [prerequisite("physics", "quantum-physics")],
  ),
  topic(
    "physics",
    "particle-physics",
    "Particle Physics",
    "Classify fundamental particles and interpret interactions through conservation laws and field models.",
    12,
    14,
    "challenging",
    String.raw`E^2=p^2c^2+m^2c^4`,
    "Energy squared equals momentum squared times light speed squared plus mass squared times light speed to the fourth",
    "For a particle at rest, p = 0 and the relation reduces to E = mc².",
    "Particle physics probes the early universe, medical imaging, materials, and the limits of known models.",
    "A particle name alone does not specify a complete interaction; charge, momentum, and conservation laws matter.",
    [prerequisite("physics", "quantum-physics"), prerequisite("physics", "nuclear-physics")],
  ),
  topic(
    "physics",
    "olympiad-physics",
    "Olympiad Physics",
    "Combine multiple models, limiting cases, diagrams, and conservation arguments in unfamiliar problems.",
    15,
    15,
    "challenging",
    String.raw`\sum F=ma`,
    "The vector sum of forces equals mass times acceleration",
    "A solution should state the system, choose axes, draw forces, and test the result against limiting cases.",
    "Olympiad physics develops model selection and disciplined reasoning across mechanics and modern topics.",
    "A long calculation is not automatically a strong solution; a clear model and checks are essential.",
    [
      prerequisite("physics", "dynamics"),
      prerequisite("physics", "energy"),
      prerequisite("physics", "momentum"),
    ],
  ),
];

const chemistryTopics: Phase20Topic[] = [
  topic(
    "chemistry",
    "atomic-structure",
    "Atomic Structure",
    "Relate nuclei, electrons, isotopes, and energy levels to the observable properties of atoms.",
    8,
    10,
    "gentle",
    String.raw`E_n=-\frac{13.6\,\mathrm{eV}}{n^2}`,
    "The hydrogen energy level is negative 13.6 electron volts divided by n squared",
    "The n = 2 hydrogen level is less negative than n = 1, so an electron there has greater energy.",
    "Atomic structure explains spectra, periodicity, bonding, materials, and astronomical composition.",
    "An isotope changes neutron number, not the element's proton number.",
  ),
  topic(
    "chemistry",
    "periodicity",
    "Periodicity",
    "Use repeating electron configurations to explain trends in atomic radius, ionization energy, and reactivity.",
    8,
    10,
    "balanced",
    String.raw`Z_{\mathrm{eff}}=Z-S`,
    "Effective nuclear charge equals nuclear charge minus shielding",
    "Across a period, increasing nuclear charge with similar shielding generally pulls valence electrons closer.",
    "Periodic trends help predict bonding, reactivity, materials, and environmental behavior.",
    "The periodic table is not only a list of atomic masses; position encodes electron structure and trends.",
    [prerequisite("chemistry", "atomic-structure")],
  ),
  topic(
    "chemistry",
    "bonding",
    "Bonding",
    "Explain how ionic, covalent, and metallic interactions organize atoms into substances with distinct properties.",
    8,
    10,
    "balanced",
    String.raw`\Delta\mathrm{EN}=|\mathrm{EN}_A-\mathrm{EN}_B|`,
    "Electronegativity difference is the absolute difference between two electronegativities",
    "A larger electronegativity difference often indicates more polar electron sharing, subject to molecular context.",
    "Bonding links microscopic structure with solubility, conductivity, shape, and biological function.",
    "A polar bond does not guarantee a polar molecule; molecular geometry can cancel bond dipoles.",
    [prerequisite("chemistry", "periodicity")],
  ),
  topic(
    "chemistry",
    "stoichiometry",
    "Stoichiometry",
    "Use balanced equations and the mole to relate amounts of reactants and products quantitatively.",
    8,
    10,
    "balanced",
    String.raw`n=\frac{m}{M}`,
    "Amount in moles equals mass divided by molar mass",
    "18 g of water is approximately 1 mol because its molar mass is about 18 g/mol.",
    "Stoichiometry supports laboratory preparation, medicine dosage, industry, and atmospheric chemistry.",
    "Coefficients in a balanced equation describe mole ratios; they are not necessarily mass ratios.",
    [prerequisite("chemistry", "atomic-structure"), prerequisite("mathematics", "arithmetic")],
  ),
  topic(
    "chemistry",
    "reactions",
    "Reactions",
    "Classify chemical transformations and balance equations while conserving atoms and charge.",
    8,
    10,
    "balanced",
    String.raw`\mathrm{reactants}\rightarrow\mathrm{products}`,
    "Reactants transform into products",
    "In a combustion equation, coefficients are adjusted so each element has the same atom count on both sides.",
    "Reaction models explain synthesis, corrosion, digestion, combustion, and environmental change.",
    "Balancing an equation changes coefficients, not the subscripts inside a chemical formula.",
    [prerequisite("chemistry", "stoichiometry"), prerequisite("chemistry", "bonding")],
  ),
  topic(
    "chemistry",
    "gases",
    "Gases",
    "Relate pressure, volume, temperature, and amount to particle motion in gases.",
    9,
    11,
    "balanced",
    String.raw`PV=nRT`,
    "Pressure times volume equals amount times the gas constant times temperature",
    "At fixed amount and temperature, doubling volume halves pressure in the ideal-gas model.",
    "Gas models support weather, respiration, engines, laboratory measurement, and planetary atmospheres.",
    "Temperature must be absolute in the ideal gas law; Celsius cannot be substituted directly for kelvin.",
    [prerequisite("chemistry", "stoichiometry")],
  ),
  topic(
    "chemistry",
    "thermochemistry",
    "Thermochemistry",
    "Track heat transfer and enthalpy changes during physical and chemical processes.",
    9,
    12,
    "challenging",
    String.raw`\Delta H=\sum H_{\mathrm{products}}-\sum H_{\mathrm{reactants}}`,
    "Enthalpy change equals product enthalpy sum minus reactant enthalpy sum",
    "An exothermic reaction has negative enthalpy change when the system releases heat to its surroundings.",
    "Thermochemistry connects fuels, metabolism, climate, materials, and laboratory calorimetry.",
    "A negative enthalpy change does not by itself prove that a reaction is fast or spontaneous.",
    [prerequisite("chemistry", "reactions"), prerequisite("physics", "thermodynamics")],
  ),
  topic(
    "chemistry",
    "kinetics",
    "Kinetics",
    "Explain reaction rate using collisions, activation energy, concentration, temperature, and catalysts.",
    10,
    12,
    "challenging",
    String.raw`\mathrm{rate}=k[A]^m[B]^n`,
    "Reaction rate equals a rate constant times reactant concentrations raised to their reaction orders",
    "A catalyst can increase rate by lowering activation energy without changing the overall reaction enthalpy.",
    "Kinetics guides medicine stability, industrial reactors, atmospheric chemistry, and enzyme studies.",
    "A catalyst changes the pathway and rate; it does not change the equilibrium constant for a reaction.",
    [prerequisite("chemistry", "reactions"), prerequisite("chemistry", "gases")],
  ),
  topic(
    "chemistry",
    "equilibrium",
    "Equilibrium",
    "Analyze reversible reactions whose forward and reverse rates become equal while concentrations remain dynamic.",
    10,
    12,
    "challenging",
    String.raw`K_c=\frac{[C]^c[D]^d}{[A]^a[B]^b}`,
    "The equilibrium constant is the product concentration terms divided by reactant concentration terms, each raised to its coefficient",
    "Changing a concentration can shift the composition, but the equilibrium constant changes only with temperature for a given reaction.",
    "Equilibrium explains buffers, solubility, industrial synthesis, and biological binding.",
    "Equilibrium does not mean equal concentrations; it means equal forward and reverse rates.",
    [prerequisite("chemistry", "kinetics"), prerequisite("chemistry", "reactions")],
  ),
  topic(
    "chemistry",
    "acids-bases",
    "Acids and Bases",
    "Use proton transfer, pH, conjugate pairs, and buffers to analyze aqueous solutions.",
    10,
    12,
    "balanced",
    String.raw`\mathrm{pH}=-\log_{10}[\mathrm{H}^+]`,
    "pH equals the negative base-ten logarithm of hydrogen-ion concentration",
    "A tenfold increase in hydrogen-ion concentration lowers pH by one unit.",
    "Acid-base chemistry supports biology, soils, oceans, medicines, and analytical measurement.",
    "A lower pH means greater acidity, but pH is logarithmic rather than a linear concentration scale.",
    [prerequisite("chemistry", "equilibrium")],
  ),
  topic(
    "chemistry",
    "electrochemistry",
    "Electrochemistry",
    "Connect oxidation-reduction reactions with electric potential, cells, and charge transfer.",
    11,
    12,
    "challenging",
    String.raw`E^\circ_{\mathrm{cell}}=E^\circ_{\mathrm{cathode}}-E^\circ_{\mathrm{anode}}`,
    "Standard cell potential equals cathode reduction potential minus anode reduction potential",
    "A positive standard cell potential indicates a thermodynamically favorable galvanic reaction under standard conditions.",
    "Electrochemistry explains batteries, corrosion, electrolysis, sensors, and energy storage.",
    "Oxidation does not always involve oxygen; it is loss of electrons in the redox definition.",
    [prerequisite("chemistry", "acids-bases"), prerequisite("chemistry", "reactions")],
  ),
  topic(
    "chemistry",
    "organic-chemistry",
    "Organic Chemistry",
    "Relate carbon skeletons, functional groups, isomerism, and reaction pathways to molecular properties.",
    10,
    12,
    "balanced",
    String.raw`\mathrm{C}_n\mathrm{H}_{2n+2}`,
    "The general formula for an acyclic saturated hydrocarbon is C sub n H sub 2n plus 2",
    "For n = 3, the alkane formula gives C₃H₈, propane.",
    "Organic chemistry supports medicines, polymers, fuels, food molecules, and biochemistry.",
    "Two molecules with the same molecular formula can have different structures and properties.",
    [prerequisite("chemistry", "bonding")],
  ),
  topic(
    "chemistry",
    "inorganic-chemistry",
    "Inorganic Chemistry",
    "Study the structures, reactions, and properties of metals, minerals, salts, and coordination compounds.",
    10,
    12,
    "balanced",
    String.raw`\mathrm{oxidation\ state}=\mathrm{charge\ bookkeeping}`,
    "Oxidation state is a bookkeeping assignment for electron ownership in a compound",
    "In a neutral oxide O²⁻, the total oxidation states of the other atoms must sum to +2.",
    "Inorganic chemistry supports catalysis, minerals, materials, water treatment, and geochemistry.",
    "An oxidation state is a model assignment, not always a directly measured localized charge.",
    [prerequisite("chemistry", "periodicity"), prerequisite("chemistry", "bonding")],
  ),
  topic(
    "chemistry",
    "analytical-chemistry",
    "Analytical Chemistry",
    "Identify substances and determine their amounts using calibration, separation, titration, and uncertainty.",
    11,
    12,
    "challenging",
    String.raw`c=\frac{n}{V}`,
    "Concentration equals amount of solute divided by solution volume",
    "A solution containing 0.20 mol in 0.50 L has concentration 0.40 mol/L.",
    "Analytical chemistry supports medicine, environmental monitoring, forensics, food science, and quality control.",
    "A precise instrument can still be inaccurate if its calibration is biased.",
    [prerequisite("chemistry", "stoichiometry"), prerequisite("chemistry", "acids-bases")],
  ),
  topic(
    "chemistry",
    "physical-chemistry",
    "Physical Chemistry",
    "Use energy, equilibrium, kinetics, and molecular models to explain why chemical systems behave as they do.",
    12,
    14,
    "challenging",
    String.raw`\Delta G=\Delta H-T\Delta S`,
    "Gibbs free-energy change equals enthalpy change minus temperature times entropy change",
    "At fixed temperature and pressure, a negative ΔG indicates a thermodynamically favorable direction, not a guaranteed fast reaction.",
    "Physical chemistry links molecules with materials, batteries, atmospheric models, and biological energetics.",
    "Spontaneous and fast are different ideas; thermodynamics and kinetics answer different questions.",
    [prerequisite("chemistry", "thermochemistry"), prerequisite("chemistry", "equilibrium")],
  ),
  topic(
    "chemistry",
    "biochemistry",
    "Biochemistry",
    "Explain how proteins, carbohydrates, lipids, nucleic acids, and energy pathways support living systems.",
    11,
    13,
    "challenging",
    String.raw`\mathrm{ATP}\rightarrow\mathrm{ADP}+\mathrm{P_i}`,
    "ATP can be hydrolyzed to ADP and inorganic phosphate while transferring usable chemical energy",
    "Cells couple ATP hydrolysis to transport, movement, and synthesis rather than releasing all energy as uncontrolled heat.",
    "Biochemistry connects chemistry with cell biology, medicine, nutrition, and biotechnology.",
    "A biochemical pathway is not a single reaction; it is a regulated network of molecular steps.",
    [prerequisite("chemistry", "organic-chemistry"), prerequisite("biology", "cell-biology")],
  ),
  topic(
    "chemistry",
    "olympiad-chemistry",
    "Olympiad Chemistry",
    "Integrate structure, stoichiometry, equilibrium, thermodynamics, and kinetics in multi-step problems.",
    15,
    15,
    "challenging",
    String.raw`\Delta H_{\mathrm{reaction}}=\sum_i n_i\Delta H_i`,
    "Reaction enthalpy can be assembled as a signed sum of enthalpy contributions",
    "A strong solution states assumptions, tracks units, and checks atom, charge, energy, and limiting-case consistency.",
    "Olympiad chemistry builds transfer between symbolic equations, particle models, and quantitative evidence.",
    "Memorizing isolated reactions is not enough when the problem requires selecting and combining models.",
    [prerequisite("chemistry", "stoichiometry"), prerequisite("chemistry", "equilibrium")],
  ),
];

const biologyTopics: Phase20Topic[] = [
  topic(
    "biology",
    "cell-biology",
    "Cell Biology",
    "Explain how membranes, organelles, energy transfer, and signaling organize the basic unit of life.",
    6,
    9,
    "gentle",
    String.raw`\mathrm{DNA}\rightarrow\mathrm{RNA}\rightarrow\mathrm{protein}`,
    "Information can flow from DNA to RNA to protein",
    "A gene's information can be transcribed into RNA and then used to assemble a protein with a specific sequence.",
    "Cell biology supports medicine, ecology, genetics, biotechnology, and understanding disease.",
    "A cell is not a bag of independent parts; organelles and membranes work together in regulated systems.",
  ),
  topic(
    "biology",
    "molecular-biology",
    "Molecular Biology",
    "Trace how DNA is replicated, expressed, repaired, and regulated at the molecular level.",
    8,
    12,
    "balanced",
    String.raw`\mathrm{DNA}\xrightarrow{\mathrm{transcription}}\mathrm{mRNA}`,
    "DNA is transcribed into messenger RNA",
    "A promoter helps determine where transcription begins; the RNA sequence then carries information to a ribosome.",
    "Molecular biology connects heredity with disease, evolution, diagnostics, and genetic engineering.",
    "Genes are not simple one-to-one labels for traits; expression depends on regulation and environment.",
    [prerequisite("biology", "cell-biology")],
  ),
  topic(
    "biology",
    "genetics",
    "Genetics",
    "Use inheritance, variation, chromosomes, and probability to explain how traits are transmitted and changed.",
    9,
    12,
    "balanced",
    String.raw`P(aa)=q^2`,
    "Under Hardy-Weinberg assumptions, the recessive homozygote frequency is q squared",
    "If q = 0.2, the expected recessive homozygote frequency is 0.04 in the idealized model.",
    "Genetics supports medicine, agriculture, conservation, evolution, and family-history reasoning.",
    "A dominant allele is not necessarily more common, stronger, or better for survival.",
    [prerequisite("biology", "molecular-biology"), prerequisite("mathematics", "probability")],
  ),
  topic(
    "biology",
    "evolution",
    "Evolution",
    "Explain how heritable variation, selection, drift, gene flow, and time change populations.",
    9,
    12,
    "balanced",
    String.raw`p'=\frac{p w_A}{\bar{w}}`,
    "The next-generation frequency depends on allele frequency, relative fitness, and mean fitness",
    "If an allele's carriers leave more surviving offspring, its frequency can increase across generations.",
    "Evolution connects genetics, ecology, anatomy, microbiology, and the history of life.",
    "Individuals do not evolve genetically during a lifetime; populations change across generations.",
    [prerequisite("biology", "genetics"), prerequisite("biology", "ecology")],
  ),
  topic(
    "biology",
    "ecology",
    "Ecology",
    "Analyze interactions among organisms, populations, communities, energy flows, and nutrient cycles.",
    7,
    12,
    "balanced",
    String.raw`\frac{dN}{dt}=rN\left(1-\frac{N}{K}\right)`,
    "Population growth equals r times population size times one minus population size divided by carrying capacity",
    "Growth slows as population size approaches carrying capacity in the logistic model.",
    "Ecology supports conservation, agriculture, public health, climate science, and resource management.",
    "A food chain is not a simple transfer of all biomass energy; most energy is lost as heat at each level.",
    [prerequisite("biology", "cell-biology")],
  ),
  topic(
    "biology",
    "anatomy",
    "Anatomy",
    "Describe the structures of organisms from tissues and organs to integrated body systems.",
    7,
    11,
    "balanced",
    String.raw`\mathrm{structure}\leftrightarrow\mathrm{function}`,
    "Biological structure and function constrain one another",
    "The thin walls of lung alveoli provide a large, short diffusion path for gas exchange.",
    "Anatomy supports clinical reasoning, biomechanics, physiology, and comparative biology.",
    "Naming a structure does not explain its function without considering connections and scale.",
    [prerequisite("biology", "cell-biology")],
  ),
  topic(
    "biology",
    "physiology",
    "Physiology",
    "Explain how body systems regulate internal conditions through transport, signaling, and feedback.",
    8,
    12,
    "balanced",
    String.raw`\mathrm{input}\rightarrow\mathrm{sensor}\rightarrow\mathrm{response}`,
    "A feedback system links an input to a sensor and a response",
    "When body temperature rises, sensors and effectors coordinate responses such as sweating and increased blood flow.",
    "Physiology connects anatomy with health, exercise, neuroscience, immunology, and medicine.",
    "Homeostasis is dynamic regulation around a range, not a perfectly fixed internal value.",
    [prerequisite("biology", "anatomy")],
  ),
  topic(
    "biology",
    "anatomy-physiology",
    "Anatomy and Physiology",
    "Bridge body structure and function through integrated examples of transport, control, and exchange.",
    7,
    12,
    "balanced",
    String.raw`\mathrm{structure}\rightarrow\mathrm{function}\rightarrow\mathrm{regulation}`,
    "Structure supports function, and function is regulated",
    "A heart chamber's wall thickness relates to the pressure it must generate and the circuit it serves.",
    "The combined view helps learners connect organ systems instead of studying isolated vocabulary.",
    "Anatomy and physiology are not separate stories; structure and function are analyzed together.",
    [prerequisite("biology", "anatomy"), prerequisite("biology", "physiology")],
  ),
  topic(
    "biology",
    "microbiology",
    "Microbiology",
    "Study microorganisms, growth, metabolism, transmission, and interactions with hosts and environments.",
    9,
    12,
    "balanced",
    String.raw`\log_{10}N_t=\log_{10}N_0+\mu t`,
    "The log of population size increases with initial log population plus growth rate times time",
    "A culture that doubles repeatedly shows a linear trend on a logarithmic growth plot during its exponential phase.",
    "Microbiology supports health, food safety, ecology, biotechnology, and planetary exploration.",
    "Not all microorganisms cause disease; most microbial interactions are neutral, beneficial, or context-dependent.",
    [prerequisite("biology", "cell-biology"), prerequisite("biology", "ecology")],
  ),
  topic(
    "biology",
    "botany",
    "Botany",
    "Explain plant structure, transport, photosynthesis, reproduction, and adaptation to environments.",
    7,
    11,
    "balanced",
    String.raw`6\mathrm{CO_2}+6\mathrm{H_2O}\xrightarrow{\mathrm{light}}\mathrm{C_6H_{12}O_6}+6\mathrm{O_2}`,
    "Six carbon dioxide molecules and six water molecules form glucose and six oxygen molecules using light",
    "Leaves capture light energy and use carbon dioxide and water to build carbohydrate while releasing oxygen.",
    "Botany supports food systems, ecosystems, climate studies, and plant biotechnology.",
    "Plants respire as well as photosynthesize; photosynthesis is not the only energy-related process in plants.",
    [prerequisite("biology", "cell-biology"), prerequisite("biology", "ecology")],
  ),
  topic(
    "biology",
    "zoology",
    "Zoology",
    "Compare animal form, behavior, development, diversity, and adaptation across evolutionary lineages.",
    7,
    11,
    "balanced",
    String.raw`\mathrm{fitness}=\frac{\mathrm{offspring\ surviving}}{\mathrm{offspring\ produced}}`,
    "A simple relative-fitness ratio compares surviving offspring with offspring produced",
    "A trait can be favored when it consistently raises the number of viable offspring in a particular environment.",
    "Zoology supports biodiversity, behavior, agriculture, veterinary science, and evolution.",
    "A useful adaptation is context-dependent; a trait can help in one environment and hinder in another.",
    [prerequisite("biology", "evolution"), prerequisite("biology", "ecology")],
  ),
  topic(
    "biology",
    "neuroscience",
    "Neuroscience",
    "Connect neurons, electrical signals, synapses, networks, and behavior across levels of organization.",
    11,
    13,
    "challenging",
    String.raw`V_m=V_{\mathrm{inside}}-V_{\mathrm{outside}}`,
    "Membrane potential equals inside potential minus outside potential",
    "Ion gradients and selective membrane permeability create voltage differences that neurons can change rapidly.",
    "Neuroscience supports medicine, psychology, computation, sensory science, and learning research.",
    "A neuron does not transmit a single undifferentiated signal; timing, synapses, and network context matter.",
    [prerequisite("biology", "physiology"), prerequisite("biology", "molecular-biology")],
  ),
  topic(
    "biology",
    "immunology",
    "Immunology",
    "Explain innate and adaptive defenses, recognition, memory, tolerance, and immune regulation.",
    11,
    13,
    "challenging",
    String.raw`\mathrm{antigen}+\mathrm{antibody}\rightleftharpoons\mathrm{complex}`,
    "An antigen and antibody can reversibly form a specific complex",
    "Specific binding can help mark a target, but an immune response also depends on cells, signals, and regulation.",
    "Immunology supports vaccines, infection control, allergies, transplantation, and cancer research.",
    "An antibody binding event is not the entire immune response; context and effector mechanisms matter.",
    [prerequisite("biology", "physiology"), prerequisite("biology", "microbiology")],
  ),
  topic(
    "biology",
    "biotechnology",
    "Biotechnology",
    "Apply biological molecules and organisms in controlled processes while evaluating evidence, risk, and ethics.",
    12,
    14,
    "challenging",
    String.raw`\mathrm{DNA}\xrightarrow{\mathrm{PCR}}2^n\mathrm{\ copies}`,
    "Idealized PCR amplification doubles a target copy count each cycle",
    "After three idealized cycles, one target molecule would become eight copies before efficiency limits are considered.",
    "Biotechnology supports diagnostics, agriculture, medicines, conservation, and environmental remediation.",
    "A laboratory method's ability to amplify DNA does not by itself prove what biological role the sequence has.",
    [prerequisite("biology", "molecular-biology"), prerequisite("biology", "genetics")],
  ),
  topic(
    "biology",
    "bioinformatics",
    "Bioinformatics",
    "Use algorithms, statistics, and biological knowledge to analyze sequences, structures, and large datasets.",
    12,
    14,
    "challenging",
    String.raw`\mathrm{identity}=\frac{\mathrm{matches}}{\mathrm{alignment\ length}}`,
    "Sequence identity equals matching aligned positions divided by alignment length",
    "An alignment with 80 matching positions out of 100 aligned positions has 80 percent identity under this simple measure.",
    "Bioinformatics supports genomics, disease research, ecology, evolution, and personalized medicine.",
    "Sequence similarity is evidence for a relationship, not proof that two genes have identical functions.",
    [prerequisite("biology", "genetics"), prerequisite("mathematics", "statistics")],
  ),
  topic(
    "biology",
    "olympiad-biology",
    "Olympiad Biology",
    "Integrate cell biology, genetics, physiology, ecology, and evolution in evidence-rich problems.",
    15,
    15,
    "challenging",
    String.raw`\Delta p=p(1-p)(w_A-w_a)`,
    "A simplified allele-frequency change depends on allele frequency, its complement, and a fitness difference",
    "The model predicts the largest potential response at intermediate allele frequencies, subject to its assumptions.",
    "Olympiad biology develops causal reasoning across scales from molecules to ecosystems.",
    "A biological explanation should connect evidence to mechanism rather than listing disconnected facts.",
    [prerequisite("biology", "genetics"), prerequisite("biology", "ecology")],
  ),
];

const astronomyTopics: Phase20Topic[] = [
  topic(
    "astronomy",
    "observational-astronomy",
    "Observational Astronomy",
    "Plan observations, estimate brightness and position, and distinguish evidence from interpretation.",
    10,
    12,
    "gentle",
    String.raw`F=\frac{L}{4\pi d^2}`,
    "Observed flux equals luminosity divided by four pi times distance squared",
    "If distance doubles while luminosity stays fixed, observed flux falls to one quarter.",
    "Observation turns the night sky into quantitative evidence for models of stars and galaxies.",
    "A brighter apparent object is not necessarily more luminous; distance and extinction also affect flux.",
    [prerequisite("physics", "measurement"), prerequisite("mathematics", "statistics")],
  ),
  topic(
    "astronomy",
    "celestial-coordinates",
    "Celestial Coordinates",
    "Locate sky objects with coordinate systems tied to the observer, Earth, and the celestial sphere.",
    10,
    12,
    "balanced",
    String.raw`\mathrm{HA}=\mathrm{LST}-\alpha`,
    "Hour angle equals local sidereal time minus right ascension",
    "An object with hour angle zero lies on the local meridian in the simplified observing model.",
    "Coordinates support telescope pointing, catalogs, navigation, and time-dependent sky maps.",
    "Right ascension and declination are not ordinary longitude and latitude on Earth's surface.",
    [
      prerequisite("astronomy", "observational-astronomy"),
      prerequisite("mathematics", "trigonometry"),
    ],
  ),
  topic(
    "astronomy",
    "solar-system",
    "Solar System",
    "Compare the Sun, planets, moons, and small bodies using scale, composition, motion, and evidence.",
    10,
    12,
    "gentle",
    String.raw`P^2=a^3`,
    "In astronomical units and years, orbital period squared is approximately semimajor axis cubed",
    "A planet at four astronomical units has an idealized period of eight years in the simplified Kepler model.",
    "Solar-system comparisons reveal how formation history and distance from the Sun shape worlds.",
    "The planets do not orbit at identical speeds or distances; orbital periods grow with semimajor axis.",
    [prerequisite("astronomy", "observational-astronomy"), prerequisite("physics", "gravitation")],
  ),
  topic(
    "astronomy",
    "planetary-science",
    "Planetary Science",
    "Study surfaces, interiors, atmospheres, climate, and histories of planets and smaller worlds.",
    11,
    13,
    "balanced",
    String.raw`T_{\mathrm{eq}}=T_\star\sqrt{\frac{R_\star}{2a}}`,
    "A simple equilibrium temperature scales with stellar temperature and the square root of stellar radius divided by twice the orbital distance",
    "Moving a planet farther from its star lowers the simple equilibrium temperature before greenhouse effects are considered.",
    "Planetary science links geology, chemistry, climate, physics, and the search for habitable environments.",
    "A calculated equilibrium temperature is not the measured surface temperature; atmospheres and surfaces alter the result.",
    [prerequisite("astronomy", "solar-system"), prerequisite("physics", "thermodynamics")],
  ),
  topic(
    "astronomy",
    "orbital-mechanics",
    "Orbital Mechanics",
    "Use energy, angular momentum, and gravity to model trajectories, transfers, and orbital stability.",
    11,
    13,
    "challenging",
    String.raw`v=\sqrt{\frac{GM}{r}}`,
    "Circular orbital speed equals the square root of gravitational constant times central mass divided by radius",
    "A lower circular orbit around the same central body requires greater speed but takes less time to complete.",
    "Orbital mechanics supports satellites, missions, exoplanets, tides, and planetary formation models.",
    "An orbit is continuous free fall under gravity; astronauts are not beyond gravity simply because they feel weightless.",
    [
      prerequisite("astronomy", "solar-system"),
      prerequisite("physics", "gravitation"),
      prerequisite("mathematics", "calculus"),
    ],
  ),
  topic(
    "astronomy",
    "stellar-physics",
    "Stellar Physics",
    "Relate stellar mass, temperature, radius, luminosity, spectra, and energy generation.",
    11,
    13,
    "challenging",
    String.raw`L=4\pi R^2\sigma T^4`,
    "Luminosity equals four pi times radius squared times the Stefan-Boltzmann constant times temperature to the fourth",
    "At the same temperature, a star with twice the radius has four times the surface-area contribution to luminosity.",
    "Stellar physics turns light into estimates of the properties and histories of distant suns.",
    "Color alone does not determine a star's full physical state; spectra, luminosity, and context add evidence.",
    [
      prerequisite("astronomy", "observational-astronomy"),
      prerequisite("physics", "thermodynamics"),
    ],
  ),
  topic(
    "astronomy",
    "stellar-evolution",
    "Stellar Evolution",
    "Trace how stars change as fuel, pressure, gravity, and composition evolve over time.",
    12,
    14,
    "challenging",
    String.raw`t_{\mathrm{MS}}\approx10^{10}\,\mathrm{yr}\left(\frac{M}{M_\odot}\right)^{-2.5}`,
    "A simplified main-sequence lifetime scales as ten billion years times mass in solar units to the negative 2.5",
    "More massive stars generally exhaust core fuel faster because their luminosities are much higher.",
    "Stellar evolution explains element production, supernovae, remnants, and the age of stellar populations.",
    "A star's mass is not constant in every evolutionary phase; winds, accretion, and explosions can change it.",
    [prerequisite("astronomy", "stellar-physics"), prerequisite("physics", "nuclear-physics")],
  ),
  topic(
    "astronomy",
    "galaxies",
    "Galaxies",
    "Compare galaxies by structure, stellar populations, gas, dark matter, and activity across cosmic time.",
    12,
    14,
    "challenging",
    String.raw`v^2=\frac{GM(r)}{r}`,
    "Circular speed squared relates to enclosed mass times G divided by radius",
    "If orbital speed stays high while radius increases, the enclosed mass inferred from the model must also increase.",
    "Galaxy studies connect stars, gas, gravity, dark matter, black holes, and cosmological history.",
    "A galaxy's visible light does not directly reveal all of the mass that influences its motion.",
    [prerequisite("astronomy", "stellar-physics"), prerequisite("physics", "gravitation")],
  ),
  topic(
    "astronomy",
    "exoplanets",
    "Exoplanets",
    "Detect and characterize planets around other stars using transits, radial velocities, and follow-up evidence.",
    12,
    14,
    "challenging",
    String.raw`\delta\approx\left(\frac{R_p}{R_\star}\right)^2`,
    "Transit depth approximately equals planet radius divided by star radius, squared",
    "A planet half the star's radius would produce a simplified transit depth of one quarter.",
    "Exoplanets connect orbital mechanics, stellar physics, statistics, instrumentation, and astrobiology.",
    "A dip in brightness alone is not enough to confirm a planet; false positives and stellar variability must be checked.",
    [
      prerequisite("astronomy", "orbital-mechanics"),
      prerequisite("astronomy", "observational-astronomy"),
    ],
  ),
  topic(
    "astronomy",
    "compact-objects",
    "Compact Objects",
    "Compare white dwarfs, neutron stars, and black holes as dense endpoints of stellar evolution.",
    12,
    14,
    "challenging",
    String.raw`R_s=\frac{2GM}{c^2}`,
    "Schwarzschild radius equals twice G times mass divided by light speed squared",
    "For a fixed mass, the characteristic relativistic radius is fixed by constants and does not depend on the object's visible surface.",
    "Compact objects test gravity, nuclear matter, high-energy emission, and gravitational-wave models.",
    "Compact does not mean all compact objects are black holes; their surfaces, fields, and mass limits differ.",
    [prerequisite("astronomy", "stellar-evolution"), prerequisite("physics", "relativity")],
  ),
  topic(
    "astronomy",
    "black-holes",
    "Black Holes",
    "Use horizons, accretion, lensing, and relativistic evidence to study regions from which light cannot escape.",
    13,
    14,
    "challenging",
    String.raw`R_s=\frac{2GM}{c^2}`,
    "The Schwarzschild radius marks the nonrotating horizon scale for a given mass",
    "The radius grows linearly with mass, so a supermassive black hole has a much larger horizon scale than a stellar one.",
    "Black holes connect relativity, high-energy astrophysics, galaxy evolution, and gravitational waves.",
    "A black hole is not a cosmic vacuum cleaner; objects can orbit it when their trajectories remain outside the horizon.",
    [prerequisite("astronomy", "compact-objects"), prerequisite("physics", "relativity")],
  ),
  topic(
    "astronomy",
    "spectroscopy",
    "Spectroscopy",
    "Read emission and absorption features to infer composition, temperature, motion, and physical conditions.",
    11,
    13,
    "balanced",
    String.raw`\frac{\lambda-\lambda_0}{\lambda_0}=\frac{v}{c}`,
    "For small radial speeds, fractional wavelength shift equals radial speed divided by light speed",
    "A redshifted line has a measured wavelength greater than its laboratory wavelength, indicating recession in the simple model.",
    "Spectroscopy lets astronomers measure distant matter without collecting a physical sample.",
    "A spectral line is not a complete fingerprint by itself; line strength and physical conditions also matter.",
    [
      prerequisite("astronomy", "observational-astronomy"),
      prerequisite("physics", "waves"),
      prerequisite("physics", "quantum-physics"),
    ],
  ),
  topic(
    "astronomy",
    "cosmology",
    "Cosmology",
    "Model the origin, expansion, contents, and large-scale structure of the universe from multiple observations.",
    12,
    14,
    "challenging",
    String.raw`v=H_0d`,
    "Recession speed equals the Hubble constant times distance in the local linear approximation",
    "A galaxy twice as far away has roughly twice the recession speed in the simple Hubble-Lemaître model.",
    "Cosmology combines galaxies, expansion, relic radiation, gravity, statistics, and the history of the universe.",
    "The expansion of space is not adequately pictured as an explosion from one ordinary location into empty space.",
    [prerequisite("astronomy", "galaxies"), prerequisite("physics", "relativity")],
  ),
  topic(
    "astronomy",
    "space-science",
    "Space Science",
    "Study the Sun-Earth system, radiation, plasma, missions, and the space environment around planets.",
    11,
    13,
    "balanced",
    String.raw`\Delta v=v_e\ln\left(\frac{m_0}{m_f}\right)`,
    "Ideal rocket delta-v equals exhaust speed times the natural log of initial mass divided by final mass",
    "Carrying more propellant can increase delta-v, but the logarithm shows why mass ratios become demanding.",
    "Space science connects engineering, planetary environments, heliophysics, radiation, and human exploration.",
    "Space is not an empty absence of hazards; radiation, particles, thermal balance, and debris all matter.",
    [prerequisite("astronomy", "solar-system"), prerequisite("physics", "measurement")],
  ),
  topic(
    "astronomy",
    "astrobiology",
    "Astrobiology",
    "Evaluate the origins, limits, and evidence for life in planetary and cosmic contexts.",
    12,
    14,
    "challenging",
    String.raw`P(\mathrm{life})=P(\mathrm{habitable})P(\mathrm{origin}\mid\mathrm{habitable})P(\mathrm{detectable}\mid\mathrm{life})`,
    "A simple life-detection probability is factored into habitability, origin, and detectability terms",
    "A world can be potentially habitable yet provide weak evidence if life is rare, hidden, or difficult to detect.",
    "Astrobiology combines biology, chemistry, geology, planetary science, and careful reasoning about evidence.",
    "A potentially habitable environment is not evidence that life is present; it is a reason to design better tests.",
    [
      prerequisite("astronomy", "planetary-science"),
      prerequisite("biology", "cell-biology"),
      prerequisite("chemistry", "biochemistry"),
    ],
  ),
];

export const phase20TopicSeed: readonly Phase20Topic[] = [
  ...mathematicsTopics,
  ...physicsTopics,
  ...chemistryTopics,
  ...biologyTopics,
  ...astronomyTopics,
];

assertValidPhase20Topics(phase20TopicSeed);

const existingDomainIds = new Set([
  "domain-arithmetic",
  "domain-algebra",
  "domain-geometry",
  "domain-trigonometry",
  "domain-calculus",
  "domain-mechanics",
  "domain-waves",
  "domain-thermodynamics",
  "domain-electricity",
  "domain-modern-physics",
  "domain-atomic-structure",
  "domain-stoichiometry",
  "domain-reactions",
  "domain-acids-bases",
  "domain-organic-chemistry",
  "domain-cell-biology",
  "domain-genetics",
  "domain-ecology",
  "domain-anatomy-physiology",
  "domain-evolution",
  "domain-observational-astronomy",
  "domain-solar-system",
  "domain-planetary-science",
  "domain-stellar-physics",
  "domain-cosmology",
]);

const domainOrders: Record<Phase20Subject, Record<string, number>> = {
  mathematics: {
    arithmetic: 1,
    algebra: 2,
    geometry: 3,
    trigonometry: 4,
    calculus: 5,
    functions: 6,
    probability: 7,
    statistics: 8,
    combinatorics: 9,
    "linear-algebra": 10,
    "differential-equations": 11,
    "number-theory": 12,
    "complex-numbers": 13,
    "discrete-mathematics": 14,
    "olympiad-mathematics": 15,
  },
  physics: {
    mechanics: 1,
    waves: 2,
    thermodynamics: 3,
    electricity: 4,
    "modern-physics": 5,
    measurement: 6,
    kinematics: 7,
    dynamics: 8,
    energy: 9,
    momentum: 10,
    rotation: 11,
    gravitation: 12,
    fluids: 13,
    magnetism: 14,
    optics: 15,
    relativity: 16,
    "quantum-physics": 17,
    "nuclear-physics": 18,
    "particle-physics": 19,
    "olympiad-physics": 20,
  },
  chemistry: {
    "atomic-structure": 1,
    stoichiometry: 2,
    reactions: 3,
    "acids-bases": 4,
    "organic-chemistry": 5,
    periodicity: 6,
    bonding: 7,
    gases: 8,
    thermochemistry: 9,
    kinetics: 10,
    equilibrium: 11,
    electrochemistry: 12,
    "inorganic-chemistry": 13,
    "analytical-chemistry": 14,
    "physical-chemistry": 15,
    biochemistry: 16,
    "olympiad-chemistry": 17,
  },
  biology: {
    "cell-biology": 1,
    genetics: 2,
    ecology: 3,
    "anatomy-physiology": 4,
    evolution: 5,
    "molecular-biology": 6,
    anatomy: 7,
    physiology: 8,
    microbiology: 9,
    botany: 10,
    zoology: 11,
    neuroscience: 12,
    immunology: 13,
    biotechnology: 14,
    bioinformatics: 15,
    "olympiad-biology": 16,
  },
  astronomy: {
    "observational-astronomy": 1,
    "solar-system": 2,
    "planetary-science": 3,
    "stellar-physics": 4,
    cosmology: 5,
    "celestial-coordinates": 6,
    "orbital-mechanics": 7,
    "stellar-evolution": 8,
    galaxies: 9,
    exoplanets: 10,
    "compact-objects": 11,
    "black-holes": 12,
    spectroscopy: 13,
    "space-science": 14,
    astrobiology: 15,
  },
};

export const phase20DomainSeed = phase20TopicSeed
  .filter((topic) => !existingDomainIds.has(topic.domainId))
  .map(
    (topic) =>
      [
        topic.domainId,
        topic.slug,
        topic.name,
        topic.description,
        topic.subjectSlug,
        domainOrders[topic.subjectSlug][topic.slug],
      ] as const,
  );

const phase20MinimumGrades = new Map(
  phase20TopicSeed.map((topic) => [topic.domainId, topic.minimumGrade]),
);

export function phase20MinimumGradeForDomain(domainId: string): number | null {
  return phase20MinimumGrades.get(domainId) ?? null;
}

const curriculumIds = [
  ["curriculum-kosovo", "kosovo"],
  ["curriculum-international", "international"],
  ["curriculum-custom", "custom"],
] as const;

function gradeIdForNumber(grade: number): string {
  if (grade <= 12) return `grade-${grade}`;
  if (grade === 13) return "grade-university-foundations";
  if (grade === 14) return "grade-advanced";
  return "grade-olympiad";
}

function gradeIdsBetween(minimumGrade: number, maximumGrade: number): string[] {
  const grades = Array.from({ length: 7 }, (_, index) => index + 6).filter(
    (grade) => grade >= minimumGrade && grade <= maximumGrade,
  );
  for (const specialGrade of [13, 14, 15]) {
    if (specialGrade >= minimumGrade && specialGrade <= maximumGrade) grades.push(specialGrade);
  }
  return grades.map(gradeIdForNumber);
}

function subjectId(subjectSlug: Phase20Subject): string {
  return `subject-${subjectSlug}`;
}

function contentId(prefix: string, topic: Phase20Topic): string {
  return `${prefix}-phase20-${topic.subjectSlug}-${topic.slug}`;
}

function objectiveId(topic: Phase20Topic, curriculumSlug: string): string {
  return `objective-phase20-${curriculumSlug}-${topic.subjectSlug}-${topic.slug}`;
}

function conceptId(topic: Phase20Topic): string {
  return contentId("concept", topic);
}

function courseId(topic: Phase20Topic): string {
  return contentId("course", topic);
}

function moduleId(topic: Phase20Topic): string {
  return contentId("module", topic);
}

function lessonId(topic: Phase20Topic): string {
  return contentId("lesson", topic);
}

function questionId(topic: Phase20Topic): string {
  return contentId("question", topic);
}

function exerciseSetId(topic: Phase20Topic): string {
  return contentId("exercise-set", topic);
}

function assessmentId(topic: Phase20Topic): string {
  return contentId("assessment", topic);
}

export const phase20ObjectiveSeed = curriculumIds.flatMap(([curriculumId, curriculumSlug]) =>
  phase20TopicSeed.map((topic, index) => ({
    id: objectiveId(topic, curriculumSlug),
    curriculumId,
    subjectId: subjectId(topic.subjectSlug),
    domainId: topic.domainId,
    code: `P20-${topic.subjectSlug.slice(0, 4).toUpperCase()}-${String(index + 1).padStart(3, "0")}`,
    title: `Apply ${topic.name}`,
    description: `Explain, model, and apply ${topic.name} at the selected progression point.`,
    difficulty: topic.difficulty,
    isRequired: topic.minimumGrade <= 10 && !topic.slug.startsWith("olympiad"),
    sortOrder: domainOrders[topic.subjectSlug][topic.slug],
    gradeId: gradeIdForNumber(topic.minimumGrade),
  })),
);

export const phase20GradeObjectiveSeed = curriculumIds.flatMap(([curriculumId, curriculumSlug]) =>
  phase20TopicSeed.flatMap((topic) =>
    gradeIdsBetween(topic.minimumGrade, topic.maximumGrade).map((gradeId, sortOrder) => ({
      curriculumId,
      gradeId,
      objectiveId: objectiveId(topic, curriculumSlug),
      isRequired: topic.minimumGrade <= 10 && !topic.slug.startsWith("olympiad"),
      sortOrder,
    })),
  ),
);

export const phase20CourseSeed = phase20TopicSeed.map((topic) => ({
  id: courseId(topic),
  slug: `phase20-${topic.subjectSlug}-${topic.slug}`,
  title: `${topic.name}: scientific foundations`,
  description: `${topic.description} Source note: ${topic.sourceAttribution}`,
  subjectId: subjectId(topic.subjectSlug),
  difficulty: topic.difficulty,
  estimatedDurationMinutes: topic.minimumGrade >= 13 ? 120 : 75,
  gradeMinId: gradeIdForNumber(topic.minimumGrade),
  gradeMaxId: gradeIdForNumber(topic.maximumGrade),
  courseImage: null,
  isRequired: topic.minimumGrade <= 10 && !topic.slug.startsWith("olympiad"),
  status: "published",
  createdByProfileId: null,
}));

export const phase20CourseCurriculumSeed = phase20CourseSeed.flatMap((course) =>
  curriculumIds.map(([curriculumId]) => [course.id, curriculumId] as const),
);

export const phase20CourseGradeSeed = phase20TopicSeed.flatMap((topic) =>
  gradeIdsBetween(topic.minimumGrade, topic.maximumGrade).map(
    (gradeId, sortOrder) =>
      [
        courseId(topic),
        gradeId,
        topic.minimumGrade <= 10 && !topic.slug.startsWith("olympiad"),
        sortOrder,
      ] as const,
  ),
);

export const phase20CourseObjectiveSeed = phase20TopicSeed.flatMap((topic) =>
  curriculumIds.map(
    ([, curriculumSlug], sortOrder) =>
      [courseId(topic), objectiveId(topic, curriculumSlug), sortOrder] as const,
  ),
);

export const phase20CoursePrerequisiteSeed = phase20TopicSeed.flatMap((topic) =>
  topic.prerequisiteKeys.flatMap((prerequisiteKey) => {
    const prerequisiteTopic = phase20TopicSeed.find(
      (candidate) => candidate.key === prerequisiteKey,
    );
    return prerequisiteTopic ? [[courseId(topic), courseId(prerequisiteTopic)] as const] : [];
  }),
);

export const phase20ModuleSeed = phase20TopicSeed.map((topic) => ({
  id: moduleId(topic),
  courseId: courseId(topic),
  title: `${topic.name} model and evidence`,
  description: `Build a usable model of ${topic.name}, then test it against a worked example and an accessible schematic.`,
  sortOrder: 0,
  estimatedStudyTimeMinutes: topic.minimumGrade >= 13 ? 120 : 75,
  assessmentReference: `Assessment: ${assessmentId(topic)}`,
}));

export const phase20LessonSeed = phase20TopicSeed.map((topic) => ({
  id: lessonId(topic),
  moduleId: moduleId(topic),
  slug: `phase20-${topic.slug}`,
  title: `${topic.name}: model, example, and evidence`,
  summary: `${topic.description} Work through the model, formula, and a concrete application.`,
  sortOrder: 0,
  estimatedDurationMinutes: topic.minimumGrade >= 13 ? 60 : 35,
  status: "published",
  currentVersionNumber: 1,
  publishedVersionId: `lesson-version-${lessonId(topic).replace("lesson-", "")}-1`,
  createdByProfileId: null,
}));

const sectionIds = (topic: Phase20Topic) => ({
  introduction: `section-phase20-${topic.subjectSlug}-${topic.slug}-introduction`,
  formal: `section-phase20-${topic.subjectSlug}-${topic.slug}-formal`,
  example: `section-phase20-${topic.subjectSlug}-${topic.slug}-example`,
  summary: `section-phase20-${topic.subjectSlug}-${topic.slug}-summary`,
});

export const phase20SectionSeed = phase20TopicSeed.flatMap((topic) => {
  const ids = sectionIds(topic);
  return [
    [
      ids.introduction,
      lessonId(topic),
      "introduction",
      "Start with the question",
      "Name the scientific question and why it matters.",
      0,
    ],
    [
      ids.formal,
      lessonId(topic),
      "formal-explanation",
      "Build the model",
      "Connect definitions, relationships, and assumptions.",
      1,
    ],
    [
      ids.example,
      lessonId(topic),
      "worked-example",
      "Worked example",
      "Use the model with units, evidence, and an explicit check.",
      2,
    ],
    [
      ids.summary,
      lessonId(topic),
      "summary",
      "Summary and next step",
      "Keep the idea connected to its prerequisite and application.",
      3,
    ],
  ] as const;
});

function escapeXml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function accessibleDiagramSource(topic: Phase20Topic): string {
  const label = escapeXml(topic.name);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 220" role="img" aria-label="${escapeXml(`Schematic overview of ${topic.name}`)}"><rect width="900" height="220" rx="24" fill="#0f172a"/><circle cx="150" cy="110" r="58" fill="#38bdf8"/><circle cx="450" cy="110" r="58" fill="#a78bfa"/><circle cx="750" cy="110" r="58" fill="#34d399"/><path d="M208 110h184M508 110h184" stroke="#e2e8f0" stroke-width="8" stroke-linecap="round"/><text x="150" y="116" text-anchor="middle" font-family="Arial" font-size="20" fill="#0f172a">evidence</text><text x="450" y="116" text-anchor="middle" font-family="Arial" font-size="20" fill="#0f172a">model</text><text x="750" y="116" text-anchor="middle" font-family="Arial" font-size="20" fill="#0f172a">prediction</text><text x="450" y="35" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="#f8fafc">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export const phase20BlockSeed = phase20TopicSeed.flatMap((topic) => {
  const ids = sectionIds(topic);
  const prerequisites = topic.prerequisiteKeys.length
    ? `Prerequisites: ${topic.prerequisiteKeys.join(", ")}.`
    : "This package starts with an accessible foundation.";
  return [
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-intro`,
      ids.introduction,
      "paragraph",
      "",
      0,
      { text: `${topic.description} ${prerequisites}` },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-heading`,
      ids.formal,
      "heading",
      topic.name,
      0,
      { level: 3, text: topic.name },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-markdown`,
      ids.formal,
      "markdown",
      "",
      1,
      {
        markdown: `${topic.description}\n\nUse the relationship below as a model, state its assumptions, and ask what evidence would support or challenge it.`,
      },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-definition`,
      ids.formal,
      "definition",
      topic.name,
      2,
      { term: topic.name, definition: topic.description },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-example`,
      ids.example,
      "example",
      "Apply the model",
      0,
      {
        prompt: topic.workedExample,
        steps: [
          "Identify the quantities or observations that are known.",
          "Choose the relationship and state the relevant assumptions.",
          "Substitute carefully, keep units visible, and interpret the result.",
        ],
      },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-formula`,
      ids.example,
      "formula",
      "Core relationship",
      1,
      { latex: topic.formula, accessibleLabel: topic.formulaLabel, display: "block" },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-diagram`,
      ids.example,
      "diagram",
      "Evidence to model to prediction",
      2,
      {
        sourceUrl: accessibleDiagramSource(topic),
        altText: `Schematic showing evidence leading to a ${topic.name} model and then to a prediction.`,
        caption: `Original Mathios Phase 20 schematic for ${topic.name}. ${topic.sourceAttribution}`,
      },
    ],
    [
      `block-phase20-${topic.subjectSlug}-${topic.slug}-summary`,
      ids.summary,
      "callout",
      "Check your model",
      0,
      {
        tone: "success",
        text: `${topic.application} Watch for this misconception: ${topic.misconception}`,
      },
    ],
  ] as const;
});

export const phase20LessonObjectiveSeed = phase20TopicSeed.map(
  (topic) => [lessonId(topic), objectiveId(topic, "kosovo"), 0] as const,
);

export const phase20ConceptSeed = phase20TopicSeed.map((topic) => ({
  id: conceptId(topic),
  slug: `phase20-${topic.subjectSlug}-${topic.slug}`,
  name: topic.name,
  description: topic.description,
  subjectId: subjectId(topic.subjectSlug),
  domainId: topic.domainId,
  gradeMinId: gradeIdForNumber(topic.minimumGrade),
  gradeMaxId: gradeIdForNumber(topic.maximumGrade),
  difficulty: topic.difficulty,
  masteryThreshold:
    topic.difficulty === "challenging" ? 80 : topic.difficulty === "balanced" ? 75 : 70,
}));

export const phase20ConceptRelationshipSeed = phase20TopicSeed.flatMap((topic) =>
  topic.prerequisiteKeys.flatMap((prerequisiteKey) => {
    const prerequisiteTopic = phase20TopicSeed.find(
      (candidate) => candidate.key === prerequisiteKey,
    );
    return prerequisiteTopic
      ? [
          [
            `concept-edge-phase20-${topic.subjectSlug}-${topic.slug}-${prerequisiteTopic.subjectSlug}-${prerequisiteTopic.slug}`,
            conceptId(topic),
            conceptId(prerequisiteTopic),
            "requires",
          ] as const,
        ]
      : [];
  }),
);

export const phase20ConceptObjectiveSeed = phase20TopicSeed.map(
  (topic) => [conceptId(topic), objectiveId(topic, "kosovo"), 0] as const,
);

export const phase20ConceptLessonSeed = phase20TopicSeed.map(
  (topic) => [conceptId(topic), lessonId(topic), 0] as const,
);

export const phase20ConceptApplicationSeed = phase20TopicSeed.map(
  (topic) =>
    [
      `application-phase20-${topic.subjectSlug}-${topic.slug}`,
      conceptId(topic),
      `Application: ${topic.name}`,
      topic.application,
      0,
    ] as const,
);

export const phase20ConceptMisconceptionSeed = phase20TopicSeed.map(
  (topic) =>
    [
      `misconception-phase20-${topic.subjectSlug}-${topic.slug}`,
      conceptId(topic),
      topic.misconception,
      `Use the definition, formula, worked example, and evidence check in the package to correct this idea.`,
      0,
    ] as const,
);

export const phase20QuestionSeed = phase20TopicSeed.map((topic) => ({
  id: questionId(topic),
  slug: `phase20-${topic.subjectSlug}-${topic.slug}`,
  title: `${topic.name} model check`,
  type: "multiple-choice",
  subjectId: subjectId(topic.subjectSlug),
  gradeMinId: gradeIdForNumber(topic.minimumGrade),
  gradeMaxId: gradeIdForNumber(topic.maximumGrade),
  difficulty: topic.difficulty,
  estimatedTimeSeconds: topic.minimumGrade >= 13 ? 180 : 120,
  source: topic.sourceAttribution,
  authorProfileId: null,
  tags: ["phase-20", topic.subjectSlug, topic.slug],
  status: "published",
  prompt: `Which statement is the most accurate starting model for ${topic.name}?`,
  answerSpec: { correctOptionKeys: ["b"] },
  explanation: `Option b preserves the core meaning of ${topic.name} and keeps the assumptions visible.`,
  fullSolution: `${topic.description} A learner should connect the relationship ${topic.formula} to evidence and its limits.`,
  commonWrongAnswers: ["It has no observable consequences."],
  errorFeedback: {
    a: "Start with the package definition and identify the quantities it connects.",
  },
  partialCreditRules: null,
  changeSummary: "Initial published Phase 20 content package.",
  options: [
    {
      id: `option-phase20-${topic.subjectSlug}-${topic.slug}-a`,
      key: "a",
      label: "It is unrelated to observation, models, or evidence.",
      sortOrder: 0,
      isCorrect: false,
    },
    {
      id: `option-phase20-${topic.subjectSlug}-${topic.slug}-b`,
      key: "b",
      label: topic.description,
      sortOrder: 1,
      isCorrect: true,
    },
    {
      id: `option-phase20-${topic.subjectSlug}-${topic.slug}-c`,
      key: "c",
      label: "It is valid only when all scientific assumptions are ignored.",
      sortOrder: 2,
      isCorrect: false,
    },
  ],
  hints: [
    {
      id: `hint-phase20-${topic.subjectSlug}-${topic.slug}-1`,
      level: 1,
      content: `Compare each option with the definition of ${topic.name}.`,
      sortOrder: 0,
    },
  ],
  solutions: [
    {
      id: `solution-phase20-${topic.subjectSlug}-${topic.slug}`,
      title: "Model check",
      content: `${topic.description} The relationship ${topic.formula} is useful only when its assumptions and units are respected.`,
      sortOrder: 0,
    },
  ],
  conceptIds: [conceptId(topic)],
  learningObjectiveIds: [objectiveId(topic, "kosovo")],
}));

export const phase20ExerciseSetSeed = phase20TopicSeed.map((topic) => ({
  id: exerciseSetId(topic),
  slug: `phase20-${topic.subjectSlug}-${topic.slug}`,
  title: `${topic.name} practice`,
  description: `A short practice set for the ${topic.name} content package.`,
  kind: "concept",
  subjectId: subjectId(topic.subjectSlug),
  gradeId: gradeIdForNumber(topic.minimumGrade),
  difficulty: topic.difficulty,
  status: "published",
  estimatedTimeSeconds: topic.minimumGrade >= 13 ? 900 : 600,
  createdByProfileId: null,
}));

export const phase20ExerciseSetQuestionSeed = phase20TopicSeed.map(
  (topic) => [exerciseSetId(topic), questionId(topic), 0, 1, true] as const,
);

export const phase20AssessmentSeed = phase20TopicSeed.map((topic) => ({
  id: assessmentId(topic),
  slug: `phase20-${topic.subjectSlug}-${topic.slug}`,
  title: `${topic.name} checkpoint`,
  description: `A published checkpoint covering the ${topic.name} model, evidence, and application.`,
  type: topic.slug.startsWith("olympiad") ? "olympiad-problem-set" : "module-quiz",
  subjectId: subjectId(topic.subjectSlug),
  gradeId: gradeIdForNumber(topic.minimumGrade),
  status: "published",
  timeLimitSeconds: topic.minimumGrade >= 13 ? 1800 : 900,
  attemptLimit: 3,
  passingThreshold: topic.difficulty === "challenging" ? 0.75 : 0.6,
  partialCredit: true,
  feedbackVisibility: "after-submit",
  reviewMode: "full",
  retakeRule: "after-failure",
  questionOrdering: "fixed",
  autoSubmit: false,
  configuration: {
    phase: "phase-20",
    contentPackageKey: topic.key,
    sourceAttribution: topic.sourceAttribution,
  },
  createdByProfileId: null,
}));

export const phase20AssessmentSectionSeed = phase20TopicSeed.map((topic) => ({
  id: `assessment-section-phase20-${topic.subjectSlug}-${topic.slug}`,
  assessmentId: assessmentId(topic),
  title: `${topic.name} model`,
  description: "Check the concept definition and its scientific limits.",
  sortOrder: 0,
  points: 1,
  timeLimitSeconds: null,
  questionOrdering: "fixed",
}));

export const phase20AssessmentQuestionSeed = phase20TopicSeed.map((topic) => ({
  id: `assessment-question-phase20-${topic.subjectSlug}-${topic.slug}`,
  assessmentId: assessmentId(topic),
  sectionId: `assessment-section-phase20-${topic.subjectSlug}-${topic.slug}`,
  poolId: null,
  questionId: questionId(topic),
  sortOrder: 0,
  points: 1,
  isRequired: true,
}));

const phase20RoadmapId = "roadmap-phase20-scientific-content";

export const phase20RoadmapSeed = [
  {
    id: phase20RoadmapId,
    slug: "phase20-scientific-content",
    title: "Scientific Content Progression",
    description: "A cross-subject progression connecting the complete Phase 20 content expansion.",
    goal: "Build transferable foundations from quantitative reasoning to advanced scientific inquiry.",
    targetGradeId: "grade-advanced",
    targetDifficulty: "challenging",
    estimatedDurationMinutes: phase20TopicSeed.length * 45,
    coverImage: null,
    status: "published",
    createdByProfileId: null,
  },
] as const;

export const phase20RoadmapSubjectSeed = [
  [phase20RoadmapId, "subject-mathematics", 0],
  [phase20RoadmapId, "subject-physics", 1],
  [phase20RoadmapId, "subject-chemistry", 2],
  [phase20RoadmapId, "subject-biology", 3],
  [phase20RoadmapId, "subject-astronomy", 4],
] as const;

const phase20RoadmapNodeId = (topic: Phase20Topic): string =>
  `roadmap-node-phase20-${topic.subjectSlug}-${topic.slug}`;

export const phase20RoadmapNodeSeed = phase20TopicSeed.map((topic, sortOrder) => ({
  id: phase20RoadmapNodeId(topic),
  roadmapId: phase20RoadmapId,
  nodeKey: topic.key,
  type: "course",
  title: `${topic.name}: scientific foundations`,
  description: topic.description,
  referenceId: courseId(topic),
  referenceTitle: `${topic.name}: scientific foundations`,
  subjectId: subjectId(topic.subjectSlug),
  isRequired: !topic.slug.startsWith("olympiad"),
  isCheckpoint: topic.maximumGrade >= 13 || topic.slug.startsWith("olympiad"),
  isOptionalBranch: topic.slug.startsWith("olympiad"),
  sortOrder,
  estimatedDurationMinutes: topic.minimumGrade >= 13 ? 120 : 75,
  metadata: {
    phase: "phase-20",
    topicKey: topic.key,
    sourceAttribution: topic.sourceAttribution,
  },
}));

function phase20RoadmapEdgeId(source: Phase20Topic, target: Phase20Topic): string {
  return `roadmap-edge-phase20-${source.subjectSlug}-${source.slug}-${target.subjectSlug}-${target.slug}`;
}

export const phase20RoadmapEdgeSeed = (() => {
  const nodesByKey = new Map(phase20TopicSeed.map((topic) => [topic.key, topic]));
  const edges: Array<{
    id: string;
    roadmapId: string;
    sourceNodeId: string;
    targetNodeId: string;
    type: "requires" | "recommended" | "optional";
    sortOrder: number;
  }> = [];
  const seen = new Set<string>();

  const addEdge = (
    source: Phase20Topic,
    target: Phase20Topic,
    type: "requires" | "recommended" | "optional",
  ) => {
    const id = phase20RoadmapEdgeId(source, target);
    if (seen.has(id)) return;
    seen.add(id);
    edges.push({
      id,
      roadmapId: phase20RoadmapId,
      sourceNodeId: phase20RoadmapNodeId(source),
      targetNodeId: phase20RoadmapNodeId(target),
      type,
      sortOrder: edges.length,
    });
  };

  for (const topic of phase20TopicSeed) {
    for (const prerequisiteKey of topic.prerequisiteKeys) {
      const prerequisiteTopic = nodesByKey.get(prerequisiteKey);
      if (prerequisiteTopic) addEdge(prerequisiteTopic, topic, "requires");
    }
    if (topic.slug.startsWith("olympiad")) {
      const previous = [...phase20TopicSeed]
        .reverse()
        .find(
          (candidate) => candidate.subjectSlug === topic.subjectSlug && candidate.key !== topic.key,
        );
      if (previous) addEdge(previous, topic, "optional");
    }
  }
  return edges;
})();

export const phase20RoadmapPrerequisiteSeed = [
  [phase20RoadmapId, "roadmap-natural-sciences-foundations", true],
] as const;
